# Setup: Load the Olist Orders Table into SQLite

CSV file → Pandas → SQLite → SQL Query → Results

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("olist.db")
print("Connected to SQLite successfully!")

Connected to SQLite successfully!

In [2]:
import os

# Look for the Olist CSVs in Colab (Drive / uploaded files) or locally
candidate_dirs = [
    "/content/drive/MyDrive/Tech Scholarship Data Science Curriculum & Materials/notebooks-&-dataset/dataset",
    "/content",
    "../Olist Dataset",
    "../../wtm_2026_mentorship/Olist Dataset",
]
DATA_DIR = next(d for d in candidate_dirs if os.path.exists(os.path.join(d, "olist_orders_dataset.csv")))
print("Loading data from:", DATA_DIR)

orders = pd.read_csv(os.path.join(DATA_DIR, "olist_orders_dataset.csv"))
orders.to_sql("orders", conn, if_exists="replace", index=False)
print(f"Orders table created in SQLite with {len(orders):,} rows!")

Loading data from: ../../wtm_2026_mentorship/Olist Dataset

Orders table created in SQLite with 99,441 rows!

# 1. Guided Practice

Try answering these questions yourself.

### Practice 1
Display the first **5 orders**.

### Practice 2
Show only `order_id` and `order_status`.

### Practice 3
Find all orders with the status `shipped`.

### Practice 4
Count the total number of delivered orders.

### Practice 5
Count orders by `order_status`.

## Practice 1 — Your Turn

In [3]:
query = """
SELECT *
FROM orders
LIMIT 5
"""

pd.read_sql_query(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

## Practice 2 — Your Turn

In [4]:
query = """
SELECT order_id, order_status
FROM orders
"""

pd.read_sql_query(query, conn)

                               order_id order_status
0      e481f51cbdc54678b7cc49136f2d6af7    delivered
1      53cdb2fc8bc7dce0b6741e2150273451    delivered
2      47770eb9100c2d0c44946d9cf07ec65d    delivered
3      949d5b44dbf5de918fe9c16f97b45f8a    delivered
4      ad21c59c0840e6cb83a9ceb5573f8159    delivered
...                                 ...          ...
99436  9c5dedf39a927c1b2549525ed64a053c    delivered
99437  63943bddc261676b46f01ca7ac2f7bd8    delivered
99438  83c1379a015df1e13d02aae0204711ab    delivered
99439  11c177c8e97725db2631073c19f07b62    delivered
99440  66dea50a8b16d9b4dee7af250b4be1a5    delivered

[99441 rows x 2 columns]

## Practice 3 — Your Turn

In [5]:
query = """
SELECT *
FROM orders
WHERE order_status = 'shipped'
"""

pd.read_sql_query(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,None,2018-06-28 00:00:00
1,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,None,2018-02-07 00:00:00
2,36530871a5e80138db53bcfd8a104d90,4dafe3c841d2d6cc8a8b6d25b35704b9,shipped,2017-05-09 11:48:37,2017-05-11 11:45:14,2017-05-11 13:21:47,None,2017-06-08 00:00:00
3,4d630f57194f5aba1a3d12ce23e71cd9,6d491c9fe2f04f6e2af6ec033cd8907c,shipped,2017-11-17 19:53:21,2017-11-18 19:50:31,2017-11-22 17:28:34,None,2017-12-13 00:00:00
4,3b4ad687e7e5190db827e1ae5a8989dd,1a87b8517b7d31373b50396eb15cb445,shipped,2018-06-28 12:52:15,2018-06-28 13:11:09,2018-07-04 15:20:00,None,2018-08-03 00:00:00
...,...,...,...,...,...,...,...,...
1102,a59ef0abffbef8ddaae23600b6ee6604,49e64271fb8eeb19851dc7e850e92204,shipped,2017-11-06 17:35:49,2017-11-07 06:31:44,2017-11-07 18:57:39,None,2017-11-24 00:00:00
1103,dab8a6c6bd6ec448df5b3a6b6cb887bc,394653a10cab83cad40d7e2713f3ab89,shipped,2018-07-14 10:12:51,2018-07-16 12:30:58,2018-07-16 14:34:00,None,2018-08-03 00:00:00
1104,492aed3c33bac22a8e04138319829283,58466c1166c377a56f6b2ae0d93ffbc0,shipped,2018-07-06 16:26:47,2018-07-06 16:35:10,2018-07-10 12:27:00,None,2018-07-26 00:00:00
1105,274a7f7e4f1c17b7434a830e9b8759b1,670af30ca5b8c20878fecdafa5ee01b9,shipped,2018-06-23 13:25:15,2018-06-23 13:40:11,2018-07-04 13:51:00,None,2018-07-24 00:00:00
1106,636cdd02667dc8d76d9296bf20a6890a,c162256b133c76f79181ce61d66545db,shipped,2018-02-17 14:31:22,2018-02-20 07:11:31,2018-02-20 19:18:58,None,2018-03-14 00:00:00

## Practice 4 — Your Turn

In [6]:
query = """
SELECT COUNT(*) AS delivered_orders
FROM orders
WHERE order_status = 'delivered'
"""

pd.read_sql_query(query, conn)

   delivered_orders
0             96478

## Practice 5 — Your Turn

In [7]:
query = """
SELECT order_status, COUNT(*) AS total_orders
FROM orders
GROUP BY order_status
"""

pd.read_sql_query(query, conn)

  order_status  total_orders
0     approved             2
1     canceled           625
2      created             5
3    delivered         96478
4     invoiced           314
5   processing           301
6      shipped          1107
7  unavailable           609

# . Assignment

Using the Olist database, write **five SQL queries**.

### Question 1
Display the first 10 records from the `orders` table.

### Question 2
Find all delivered orders.

### Question 3
Count the total number of orders.

### Question 4
Count the number of orders for each order status.

### Question 5
Sort the order statuses from the highest number of orders to the lowest.

For every question:

1. Write the SQL query.
2. Run the query.
3. Look at the output.
4. Write **1–2 sentences explaining what the result tells you**.

### Question 1 — First 10 records

In [8]:
query = """
SELECT *
FROM orders
LIMIT 10
"""

pd.read_sql_query(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00

**What the result tells us:** Each row is one order with its customer, status and the timestamps for purchase, approval, carrier hand-off, customer delivery and estimated delivery. The dates are stored as text, so they would need converting before doing date calculations.

### Question 2 — Delivered orders

In [9]:
query = """
SELECT *
FROM orders
WHERE order_status = 'delivered'
"""

pd.read_sql_query(query, conn)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
96473,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
96474,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
96475,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
96476,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
96477,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

**What the result tells us:** 96,478 orders have the status `delivered`, so the vast majority of orders reached the customer. A few of these (8) still have an empty `order_delivered_customer_date`, which is a data quality issue worth checking.

### Question 3 — Total number of orders

In [10]:
query = """
SELECT COUNT(*) AS total_orders
FROM orders
"""

pd.read_sql_query(query, conn)

   total_orders
0         99441

**What the result tells us:** The `orders` table contains 99,441 orders in total. This matches the number of rows we loaded from the CSV, so no data was lost when moving from Pandas into SQLite.

### Question 4 — Orders per status

In [11]:
query = """
SELECT order_status, COUNT(*) AS total_orders
FROM orders
GROUP BY order_status
"""

pd.read_sql_query(query, conn)

  order_status  total_orders
0     approved             2
1     canceled           625
2      created             5
3    delivered         96478
4     invoiced           314
5   processing           301
6      shipped          1107
7  unavailable           609

**What the result tells us:** There are 8 different order statuses. Grouping shows how orders are spread across the fulfilment pipeline, from `created` and `approved` through to `delivered`, `canceled` and `unavailable`.

### Question 5 — Statuses sorted from most to fewest orders

In [12]:
query = """
SELECT order_status, COUNT(*) AS total_orders
FROM orders
GROUP BY order_status
ORDER BY total_orders DESC
"""

pd.read_sql_query(query, conn)

  order_status  total_orders
0    delivered         96478
1      shipped          1107
2     canceled           625
3  unavailable           609
4     invoiced           314
5   processing           301
6      created             5
7     approved             2

**What the result tells us:** `delivered` (96,478) is by far the most common status, followed by `shipped` (1,107), `canceled` (625) and `unavailable` (609). Only about 3% of orders are not delivered, but canceled and unavailable orders together (1,234) are lost sales worth investigating.